Style/Documentation:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
AllCops:
  Exclude:
    - "db/**/*"
    - "bin/*"
Metrics/MethodLength:
  Max: 20
Metrics/BlockLength:
  Max: 100
Layout/LineLength:
  Max: 150